site_name: Demo Coin
pages:
    - Home: index.md
    - Prerequisites: prerequisites.md
    - Setup the project: setup_project.md
    - ERC20 Token: erc20_token.md
    - Deploy script: writing_deploy_script.md
    - Run the project: run_project.md
